specversion = "0.2"

[[capability]]
resource = "messaging.azsbus"
name = "my-messaging"
    [capability.configs]
    AZURE_SERVICE_BUS_NAMESPACE = "${envvars.AZURE_SERVICE_BUS_NAMESPACE}"
    AZURE_POLICY_NAME = "${envvars.AZURE_POLICY_NAME}"
    AZURE_POLICY_KEY = "${envvars.AZURE_POLICY_KEY}"
