apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: raw-order-subscription
  rawPayload: "true"
spec:
  topic: t-order-ingress-dapr
  route: /rawpayload
  pubsubname: order-pubsub
  metadata:
    rawPayload: "true"
scopes:
  - daprdistributor