apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: q-order-express-dapr
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: SERVICEBUS_CONNECTION
        key: SERVICEBUS_CONNECTION
    - name: queueName
      value: q-order-express-dapr
auth:
  secretStore: secretfile

