apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-pubsub
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: SERVICEBUS_CONNECTION
        key:  SERVICEBUS_CONNECTION
auth:
  secretStore: secretfile